/**
 * modules/capture.js
 * ─────────────────────────────────────────────────────────────────
 * Captures the current scene configuration and formats it as:
 *   • Clean JSON
 *   • Ready-to-copy Three.js code snippet
 * Also handles Save (download JSON) and Load (read JSON file).
 * ─────────────────────────────────────────────────────────────────
 */
import * as THREE from 'three';

export class CaptureManager {
  /**
   * @param {THREE.PerspectiveCamera} camera
   * @param {OrbitControls}           orbitControls
   * @param {object}                  state  - shared mutable state
   */
  constructor(camera, orbitControls, state) {
    this.camera = camera;
    this.orbitControls = orbitControls;
    this.state = state;

    this._panel = document.getElementById('capture-panel');
    this._jsonEl = document.getElementById('json-output');
    this._codeEl = document.getElementById('code-output');
    this._fileInput = document.getElementById('file-input');

    this._bindCopyButtons();
    this._bindTabs();
    this._bindCloseButton();
    this._bindFileInput();
  }

  // ── Public API ──────────────────────────────────────────────────

  /** Generate config, populate the panel, and show it. */
  open(gsapCode = '') {
    const cfg = this._buildConfig();
    this._jsonEl.textContent = JSON.stringify(cfg, null, 2);
    this._codeEl.textContent = this._buildCodeSnippet(cfg);
    document.getElementById('gsap-output').textContent = gsapCode;
    this._panel.classList.remove('hidden');
  }

  close() {
    this._panel.classList.add('hidden');
  }

  /** Download config as .json file */
  save() {
    const cfg = this._buildConfig();
    const blob = new Blob([JSON.stringify(cfg, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scene-config-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  /** Open file picker to load a saved config */
  triggerLoad() {
    this._fileInput.click();
  }

  /** Apply a loaded config object to the scene */
  apply(cfg) {
    const { camera: c, model: m } = cfg;

    // Camera
    this.camera.position.set(c.position.x, c.position.y, c.position.z);
    this.camera.fov = c.fov ?? 60;
    this.camera.updateProjectionMatrix();
    this.orbitControls.target.set(c.target.x, c.target.y, c.target.z);
    this.orbitControls.update();

    // Model
    if (m && this.state.model) {
      const mdl = this.state.model;
      mdl.position.set(m.position.x, m.position.y, m.position.z);
      mdl.rotation.set(
        THREE.MathUtils.degToRad(m.rotation.x),
        THREE.MathUtils.degToRad(m.rotation.y),
        THREE.MathUtils.degToRad(m.rotation.z)
      );
      mdl.scale.set(m.scale.x, m.scale.y, m.scale.z);
    }
  }

  // ── Private ─────────────────────────────────────────────────────

  _buildConfig() {
    const cam = this.camera;
    const tgt = this.orbitControls.target;
    const mdl = this.state.model;

    const config = {
      timestamp: new Date().toISOString(),
      camera: {
        position: this._v3(cam.position),
        rotation: this._euler(cam.rotation),
        target: this._v3(tgt),
        fov: +cam.fov.toFixed(2),
        near: cam.near,
        far: cam.far,
      },
      model: mdl ? {
        position: this._v3(mdl.position),
        rotation: {
          x: +THREE.MathUtils.radToDeg(mdl.rotation.x).toFixed(4),
          y: +THREE.MathUtils.radToDeg(mdl.rotation.y).toFixed(4),
          z: +THREE.MathUtils.radToDeg(mdl.rotation.z).toFixed(4),
        },
        scale: this._v3(mdl.scale),
      } : null,
    };
    return config;
  }

  _buildCodeSnippet(cfg) {
    const c = cfg.camera;
    const m = cfg.model;
    const deg2rad = (d) => +(d * Math.PI / 180).toFixed(6);

    let snippet = `// ── Generated by Three.js Scene Simulator ──
// Timestamp: ${cfg.timestamp}

// Camera setup
camera.fov = ${c.fov};
camera.near = ${c.near};
camera.far = ${c.far};
camera.updateProjectionMatrix();
camera.position.set(${c.position.x}, ${c.position.y}, ${c.position.z});

// If using OrbitControls:
controls.target.set(${c.target.x}, ${c.target.y}, ${c.target.z});
controls.update();
`;

    if (m) {
      snippet += `
// Model transform
model.position.set(${m.position.x}, ${m.position.y}, ${m.position.z});
model.rotation.set(
  ${deg2rad(m.rotation.x)}, // ${m.rotation.x}°
  ${deg2rad(m.rotation.y)}, // ${m.rotation.y}°
  ${deg2rad(m.rotation.z)}  // ${m.rotation.z}°
);
model.scale.set(${m.scale.x}, ${m.scale.y}, ${m.scale.z});
`;
    }
    return snippet;
  }

  _v3(v) { return { x: +v.x.toFixed(4), y: +v.y.toFixed(4), z: +v.z.toFixed(4) }; }
  _euler(e) { return { x: +e.x.toFixed(6), y: +e.y.toFixed(6), z: +e.z.toFixed(6) }; }

  _bindCopyButtons() {
    document.getElementById('btn-copy-json').addEventListener('click', () => {
      navigator.clipboard.writeText(this._jsonEl.textContent);
      this._flash('btn-copy-json', 'Copied!');
    });
    document.getElementById('btn-copy-code').addEventListener('click', () => {
      navigator.clipboard.writeText(this._codeEl.textContent);
      this._flash('btn-copy-code', 'Copied!');
    });
    const gsapCopyBtn = document.getElementById('btn-copy-gsap');
    if (gsapCopyBtn) {
      gsapCopyBtn.addEventListener('click', () => {
        navigator.clipboard.writeText(document.getElementById('gsap-output').textContent);
        this._flash('btn-copy-gsap', 'Copied!');
      });
    }
  }

  _bindTabs() {
    document.querySelectorAll('.cap-tab').forEach((tab) => {
      tab.addEventListener('click', () => {
        document.querySelectorAll('.cap-tab').forEach(t => t.classList.remove('active'));
        document.querySelectorAll('.cap-content').forEach(c => c.classList.remove('active'));
        tab.classList.add('active');
        document.getElementById(tab.dataset.target).classList.add('active');
      });
    });
  }

  _bindCloseButton() {
    document.getElementById('btn-close-panel').addEventListener('click', () => this.close());
  }

  _bindFileInput() {
    this._fileInput.addEventListener('change', (e) => {
      const file = e.target.files[0];
      if (!file) return;
      const reader = new FileReader();
      reader.onload = (ev) => {
        try {
          const cfg = JSON.parse(ev.target.result);
          this.apply(cfg);
          console.log('[Simulator] Config loaded:', cfg);
        } catch (err) {
          console.error('[Simulator] Failed to parse config JSON:', err);
        }
      };
      reader.readAsText(file);
      // Reset so the same file can be reloaded
      e.target.value = '';
    });
  }

  _flash(btnId, label) {
    const btn = document.getElementById(btnId);
    const orig = btn.textContent;
    btn.textContent = label;
    setTimeout(() => { btn.textContent = orig; }, 1200);
  }
}
